### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by jfuechsl** [h3poteto/logist#9]
Hello,
are there any plans for releasing a new version to rubygems.org?

**Comment by h3poteto** [comment]
I'm waiting for this pull request: https://github.com/h3poteto/logist/pull/6
but no response.
So I will release new version.

**Comment by h3poteto** [comment]
Released.
https://github.com/h3poteto/logist/releases/tag/v0.1.1

**Comment by jfuechsl** [comment]
Thank you very much!
